In [ ]:
import numpy as np

In [ ]:
age_list=[10,5,8,32,65,43]

In [ ]:
print (age_list)

[10, 5, 8, 32, 65, 43]


In [ ]:
age=np.array(age_list)
print(type(age))
print(age)

<class 'numpy.ndarray'>
[10  5  8 32 65 43]


In [ ]:
age.dtype

dtype('int64')

In [ ]:
age.size

6

In [ ]:
age.shape

(6,)

In [ ]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr=np.zeros((2,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Multi Dim

In [ ]:
weight_list=[32,18,26,60,55,65]
weight_list

[32, 18, 26, 60, 55, 65]

In [ ]:
people=np.array([age_list,weight_list])
people

array([[10,  5,  8, 32, 65, 43],
       [32, 18, 26, 60, 55, 65]])

In [ ]:
people.size

12

In [ ]:
people.shape

(2, 6)

In [ ]:
people.dtype

dtype('int64')

In [ ]:
print(type(people))

<class 'numpy.ndarray'>


In [ ]:
people=people.reshape(12,1)
print(people)
print(people.size)
print(people.dtype)

[[10]
 [ 5]
 [ 8]
 [32]
 [65]
 [43]
 [32]
 [18]
 [26]
 [60]
 [55]
 [65]]
12
int64


In [ ]:
print(type(people))

<class 'numpy.ndarray'>


EXERCISE

In [ ]:
import numpy as np

In [ ]:
list=[7, 9, 65, 33, 85, 99]

In [ ]:
arr=np.array(list)
arr

array([ 7,  9, 65, 33, 85, 99])

In [ ]:
list=[1,2,4,2,3,0,0,5,1]

In [ ]:
arr=np.array(list)
arr

array([1, 2, 4, 2, 3, 0, 0, 5, 1])

In [ ]:
arr=arr.reshape(3,3)
print(arr)

[[1 2 4]
 [2 3 0]
 [0 5 1]]


In [ ]:
arr=arr.reshape(9,1)
arr

array([[1],
       [2],
       [4],
       [2],
       [3],
       [0],
       [0],
       [5],
       [1]])

Array Generation

The np.arange() method creates a range of numbers with user defined steps between each.

In [ ]:
five_times_table = np.arange(0, 55, 5)
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

The np.linspace() method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.

In [ ]:
five_spaced = np.linspace(0,50,11)
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


The .repeat() method will repeat an object you pas a specified number of times.

In [ ]:
twoArr = np.repeat(2, 10)
print(twoArr)

[2 2 2 2 2 2 2 2 2 2]


The np.eye() functions will create an identity matrix/array for us.

In [ ]:
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


OPERATIONS

In [ ]:
print(five_times_table)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [ ]:
print("1:", 2 * five_times_table)
print("2:", 10 + five_times_table)
print("3:", five_times_table - 1)
print("4:", five_times_table/5)
print("5:", five_times_table **2)
print("6:", five_times_table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


Speed Test-
If we compare the speed at which we can do these operations compared to core python, we will notice a substantial difference.

In [ ]:
fives_list = np.arange(0,5001,5)
print(fives_list)

[   0    5   10 ... 4990 4995 5000]


In [ ]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [ ]:
%timeit five_times_table_lge + 5

1.53 µs ± 303 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
%timeit [e + 5 for e in fives_list]

239 µs ± 5.63 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Boolean string operations can also be performed on ndarrays.

In [ ]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

Transpose

In [ ]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]] 

[[10 32]
 [ 5 18]
 [ 8 26]
 [32 60]
 [65 55]
 [43 65]]


DATATYPE

In [ ]:
people.dtype

dtype('int64')

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

In [ ]:
ages_with_strings.dtype

dtype('<U21')

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

In [ ]:
ages_with_strings.dtype

dtype('int32')

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)

['10' '5' '8' '32' '65' '43']


In [ ]:
ages_with_strings.dtype

dtype('<U21')

In [ ]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [ ]:
ages_with_strings.size

126

In [ ]:
ages_with_strings.size/21

6.0

In [ ]:
np.array([10, 5, 8, '32', '65', '43']).size

6

The correct way to have changed the data type of the ndarray would have been to use the .astype() method, demonstrated below.

In [ ]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


Exercise

In [ ]:
strings = np.array(['10', '5', '8', '32', '65', '43'])
print(strings)
print(strings.astype('float'))

['10' '5' '8' '32' '65' '43']
[10.  5.  8. 32. 65. 43.]


In [ ]:
strings.shape = (2, 3)
print(strings, "\n")
print(strings.T)

[['10' '5' '8']
 ['32' '65' '43']] 

[['10' '32']
 ['5' '65']
 ['8' '43']]


In [ ]:
strings = np.array(['10', '5', '8', '32', '65', '43'])
print(strings)
print(strings.astype('bool'))

['10' '5' '8' '32' '65' '43']
[ True  True  True  True  True  True]


Array Slicing Operations

In [ ]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
five_times_table[0]

0

In [ ]:
five_times_table[-1]

50

In [ ]:
five_times_table[4:]

array([20, 25, 30, 35, 40, 45, 50])

In [ ]:
five_times_table[:4]

array([ 0,  5, 10, 15])

In [ ]:
print(people)
people[:3, :3]

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]]


array([[10,  5,  8],
       [32, 18, 26]])

EXERCISE
Create a numpy array with 50 zeros
Create a np array of 2 repeated 20 times
Create a numpy array from 0 to 2  in steps of 0.1
For one of the arrays generated:

Get the first five values
Get the last 3 values
Get the 4th value to the 7th value

In [ ]:
arr=np.zeros(50)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
rp=np.repeat(2,20)
rp

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
space=np.arange(0,(2*22/7),0.1)
space

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [ ]:
arr[0:5]

array([0., 0., 0., 0., 0.])

In [ ]:
rp[0:5]

array([2, 2, 2, 2, 2])

In [ ]:
space[0:5]

array([0. , 0.1, 0.2, 0.3, 0.4])

In [ ]:
space[-3:]

array([6. , 6.1, 6.2])

In [ ]:
space[3:7]

array([0.3, 0.4, 0.5, 0.6])

In [ ]:
reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [ ]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)
five_times_table

[50 45 40 35 30 25 20 15 10  5  0]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
five_times_table[0::3]

array([ 0, 15, 30, 45])

Exercise
#### Reverse it

#### Only keep every 4th element.
#### Get every 2nd element, starting from the last and moving backwards.

In [ ]:
new_list=[3,6,9,12,15,18,21,24,27,30,33,36,39,42]
new_array=np.array(new_list)

In [ ]:
reverse_new_array=np.flip(new_list)
reverse_new_array

array([42, 39, 36, 33, 30, 27, 24, 21, 18, 15, 12,  9,  6,  3])

In [ ]:
new_array[0::4]

array([ 3, 15, 27, 39])

In [ ]:
new_array[::2]

array([ 3,  9, 15, 21, 27, 33, 39])

Stats

In [ ]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [ ]:
nums = np.arange(0, 4, 0.2555)
nums

array([0.    , 0.2555, 0.511 , 0.7665, 1.022 , 1.2775, 1.533 , 1.7885,
       2.044 , 2.2995, 2.555 , 2.8105, 3.066 , 3.3215, 3.577 , 3.8325])

Exercise
Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [ ]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


Random

With np.random, we can generate a number of types of dataset, and create training data.

The below code simulates a fair coin toss.

In [ ]:
flip = np.random.choice([0,1], 10)
flip

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 0])

In [ ]:
np.random.rand(10,20,9)

array([[[0.91931441, 0.45547638, 0.82021861, ..., 0.45306743,
         0.28123837, 0.57394065],
        [0.00617422, 0.59007897, 0.24289226, ..., 0.28862867,
         0.70783893, 0.88785123],
        [0.2495359 , 0.87196108, 0.86540137, ..., 0.02371967,
         0.2701208 , 0.67484125],
        ...,
        [0.00195436, 0.79774971, 0.05919705, ..., 0.41369375,
         0.91669057, 0.61215167],
        [0.18239098, 0.33961348, 0.68455381, ..., 0.08138931,
         0.3221802 , 0.48887879],
        [0.07043104, 0.57580784, 0.78402372, ..., 0.13711909,
         0.8630706 , 0.20664975]],

       [[0.21171158, 0.59764142, 0.44535077, ..., 0.62764161,
         0.43978761, 0.78018192],
        [0.34333803, 0.67325788, 0.82037455, ..., 0.28789318,
         0.35709871, 0.34338484],
        [0.08127315, 0.52284199, 0.87940015, ..., 0.73777151,
         0.14803939, 0.25138792],
        ...,
        [0.68404921, 0.83672827, 0.01077244, ..., 0.20701973,
         0.02537038, 0.89696503],
        [0.6

We can produce 1000 datapoints of a normally distributed data set by using np.random.normal()

In [ ]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)
s

array([-1.33084126e-02,  2.73798102e-02,  1.27147702e-01,  1.65273640e-01,
        4.30355858e-02,  1.86433041e-02,  2.07034932e-01,  1.50690960e-01,
       -2.18639629e-01,  1.21989586e-01,  8.96090774e-02,  2.03552593e-01,
       -1.66284447e-02, -1.72077617e-01,  9.12442136e-02, -1.31910929e-01,
        2.07454868e-02, -1.88311009e-02, -5.03737787e-02, -2.74426235e-02,
        8.39975717e-02, -3.91374052e-02,  2.84055429e-02,  2.55633356e-03,
       -7.81665697e-02, -1.23989374e-01,  1.98780821e-02,  1.06347508e-01,
        1.39933249e-01,  9.17898643e-02,  3.98389212e-02, -1.86638342e-01,
        1.32240392e-02,  6.11017055e-02, -4.31613887e-02, -3.80928915e-02,
       -1.00439685e-01,  4.08329318e-02,  3.28154146e-02, -1.06011424e-01,
       -4.56288934e-02,  1.32272617e-01,  2.89401634e-02,  1.10317653e-01,
        7.83020971e-02, -1.39307529e-01,  1.64557986e-02,  1.40575900e-02,
        1.07964781e-02,  8.70949693e-02,  3.14879394e-03,  8.59296825e-03,
       -3.48922088e-02, -

Exercise

Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.

In [ ]:
throw_dice= np.random.choice([1,2,3,4,5,6], 10)
throw_dice

array([6, 6, 6, 6, 1, 3, 4, 5, 4, 5])

In [ ]:
toss=np.random.choice([0,1,1],10)
toss

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 0])